site_name: "Evennia Manual"
use_directory_urls: false
theme: windmill
nav:
  - Home: index.md
  - Admin: Administrative-Docs.md
  - Building: Builder-Docs.md
  - Game Development: Developer-Central.md
  - Tutorials: Tutorials.md
markdown_extensions:
  - wikilinks: 
      end_url: .html
  - toc:
      permalink: true
plugins:
  - search
    # - git-revision-date
    #   - macros
    # - htmlproofer
extra:
  logo: img/evennia_logo.png
  version: 0.9
  history_buttons: true
