site_name: "Evennia Manual"
use_directory_urls: false
nav:
  - Home: index.md
  - Admin: Administrative-Docs.md
  - Building: Builder-Docs.md
  - Game Development: Developer-Central.md
  - Tutorials: Tutorials.md
markdown_extensions:
  - wikilinks: 
      end_url: .html
  - toc:
      permalink: true
plugins:
  - search
  - macros
    # - htmlproofer
